### ISSUE TITLE
Suggestion to improve day 2 part 1 submission

### ISSUE THREAD

**Issue by iptcyq** [YeoJunMing/aoc22#1]
A possible way to shorten code for your method of _directly comparing to the correct string_ would be to put the "winning", "losing" and "draw" strings into their respective _arrays_, then use if statements to _check which array the string is in_. 
So instead of having 1 if statement per possible circumstance, you would just have a few to check which array, which is the winning state, it should be under.

**Pseudocode** example:
```
string win_array[] = {"winning string 1", "winning string 2", "eg A X or something"}
string draw_array[] = {"draw string 1", "draw string 2"}

string string_to_be_checked = "A X"

if (string_to_be_checked is in win_array) { add points for win }
else if (string_to_be_checked is in drwa_array) { add points for draw }
else { //would be a loss so 0 points }

```

Then to add points according to rock, paper, scissors, you can put them into an _array_ and find their _index_ to get respective points.

**Pseudocode** example:
```
string moves[] = {"rock", "paper", "scissors"} //rock 1 point .. etc

string move = "rock"

points += (index of move in moves)
```

It may be more troublesome to code than the bruteforce method but it's just a suggestion to make the code more aesthetically pleasing to the eye. :P

**Comment by YeoJunMing** [comment]
Hi thanks for the suggestion and the pseudocode examples :D I'll definitely try out that method though  it might be a little more challenging
